trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: Install Python 3.7
  - script: pip install --user tox
    displayName: Install tox
  - script: tox --notest
    displayName: Install test requirements
  - script: tox
    displayName: Run tests
